# version: "3.8"
# services:
#   ts-starter-api:
#     platform: linux/x86_64 # Critical so Prisma runs correctly on a M1 Mac
#     build: ./
#     environment:
#       NODE_ENV: development
#     ports:
#       - 8080:8080
#       - 9240:9240 # Node inspect
#     volumes:
#       - ./:/home/app/api
#       - /home/app/api/node_modules
#     working_dir: /home/app/api
#     restart: on-failure
#     depends_on:
#       - ts-starter-db
#       - redis
#   ts-starter-db:
#     image: postgres
#     environment:
#       - POSTGRES_USER=user
#       - POSTGRES_DB=ts-starter
#       - POSTGRES_PASSWORD=password
#       - POSTGRES_HOST_AUTH_METHOD=trust
#       - PGDATA=/var/lib/postgresql/data/pgdata # Critical for Postgres to work in the container
#     volumes:
#       - ./db/data/postgres:/var/lib/postgresql
#     ports:
#       - 5432:5432
